backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/docs/.vuepress/public/images"

public_folder: "images"

collections:
  - name: "Page"
    label: "Blog"
    folder: "docs/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "coverImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}